Lmod has detected the following error: The following module(s) are unknown:
"pytorch/1.4.0" "cuda/10.0.13"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore-cache load "pytorch/1.4.0" "cuda/10.0.13"



Couldn't import umap
Sampling dataset of 300000 training examples
Dataset Crops
    Number of datapoints: 287858
    Root Location: data/Crops
    Reduce: average

Traceback (most recent call last):
  File "run_models.py", line 130, in <module>
    data_obj = parse_datasets(args, device)
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod/lib/parse_datasets.py", line 226, in parse_datasets
    train_data = train_dataset_obj[:n_samples]
  File "/cluster/work/igp_psr/metzgern/ODEcrop/latent_ode-my_mod/crop_classification.py", line 798, in __getitem__
    mask = torch.from_numpy(  self.hdf5dataloader["mask"][i] )
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/cluster/home/metzgern/.local/lib/python3.7/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
KeyboardInterrupt
